# Generated by Django 3.0.1 on 2019-12-28 05:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KeyVal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.TextField(db_index=True, unique=True)),
                ('value', models.TextField()),
                ('ttl', models.DateTimeField(default=datetime.datetime(2019, 12, 28, 5, 5, 51, 264624, tzinfo=utc))),
            ],
            options={
                'verbose_name': 'Key Value',
                'verbose_name_plural': 'KeyValues',
                'db_table': 'key_values',
            },
        ),
    ]
